/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiRankingRouteImport } from './routes/api/ranking'
import { Route as ApiQueueRouteImport } from './routes/api/queue'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiLoopsRouteImport } from './routes/api/loops'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiContingencyRouteImport } from './routes/api/contingency'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as AppWarmupRouteImport } from './routes/_app.warmup'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppContingencyRouteImport } from './routes/_app.contingency'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as ApiVariantsBuildRouteImport } from './routes/api/variants.build'
import { Route as ApiRankingDailyRouteImport } from './routes/api/ranking.daily'
import { Route as ApiQueueClearRouteImport } from './routes/api/queue.clear'
import { Route as ApiQueueIdRouteImport } from './routes/api/queue.$id'
import { Route as ApiModelsIdRouteImport } from './routes/api/models.$id'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media.upload'
import { Route as ApiLoopsIdRouteImport } from './routes/api/loops.$id'
import { Route as ApiHistoryRefreshRouteImport } from './routes/api/history.refresh'
import { Route as ApiCronTickRouteImport } from './routes/api/cron.tick'
import { Route as ApiContingencyIdRouteImport } from './routes/api/contingency.$id'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthInstagramRouteImport } from './routes/api/auth.instagram'
import { Route as ApiAuthCallbackIgRouteImport } from './routes/api/auth.callback-ig'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth.callback'
import { Route as ApiAccountsIdRouteImport } from './routes/api/accounts.$id'
import { Route as ApiPublicDriveIdRouteImport } from './routes/api/public/drive.$id'
import { Route as ApiDriveFolderIdRouteImport } from './routes/api/drive.folder.$id'
import { Route as ApiAuthInstagramLinkRouteImport } from './routes/api/auth.instagram.link'
import { Route as ApiAuthInstagramCallbackRouteImport } from './routes/api/auth.instagram.callback'
import { Route as ApiAccountsIdValidateRouteImport } from './routes/api/accounts.$id.validate'
import { Route as ApiAccountsIdStatusRouteImport } from './routes/api/accounts.$id.status'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRankingRoute = ApiRankingRouteImport.update({
  id: '/api/ranking',
  path: '/api/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoopsRoute = ApiLoopsRouteImport.update({
  id: '/api/loops',
  path: '/api/loops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContingencyRoute = ApiContingencyRouteImport.update({
  id: '/api/contingency',
  path: '/api/contingency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarmupRoute = AppWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppContingencyRoute = AppContingencyRouteImport.update({
  id: '/contingency',
  path: '/contingency',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const ApiVariantsBuildRoute = ApiVariantsBuildRouteImport.update({
  id: '/api/variants/build',
  path: '/api/variants/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingDailyRoute = ApiRankingDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => ApiRankingRoute,
} as any)
const ApiQueueClearRoute = ApiQueueClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdRoute = ApiQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiModelsIdRoute = ApiModelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiModelsRoute,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoopsIdRoute = ApiLoopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLoopsRoute,
} as any)
const ApiHistoryRefreshRoute = ApiHistoryRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiHistoryRoute,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContingencyIdRoute = ApiContingencyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContingencyRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramRoute = ApiAuthInstagramRouteImport.update({
  id: '/api/auth/instagram',
  path: '/api/auth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackIgRoute = ApiAuthCallbackIgRouteImport.update({
  id: '/api/auth/callback-ig',
  path: '/api/auth/callback-ig',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsIdRoute = ApiAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAccountsRoute,
} as any)
const ApiPublicDriveIdRoute = ApiPublicDriveIdRouteImport.update({
  id: '/api/public/drive/$id',
  path: '/api/public/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFolderIdRoute = ApiDriveFolderIdRouteImport.update({
  id: '/api/drive/folder/$id',
  path: '/api/drive/folder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramLinkRoute = ApiAuthInstagramLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ApiAuthInstagramRoute,
} as any)
const ApiAuthInstagramCallbackRoute =
  ApiAuthInstagramCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramRoute,
  } as any)
const ApiAccountsIdValidateRoute = ApiAccountsIdValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => ApiAccountsIdRoute,
} as any)
const ApiAccountsIdStatusRoute = ApiAccountsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAccountsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/contingency': typeof AppContingencyRoute
  '/history': typeof AppHistoryRoute
  '/queue': typeof AppQueueRoute
  '/ranking': typeof AppRankingRoute
  '/warmup': typeof AppWarmupRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/contingency': typeof ApiContingencyRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/loops': typeof ApiLoopsRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/api/ranking': typeof ApiRankingRouteWithChildren
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/contingency/$id': typeof ApiContingencyIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/history/refresh': typeof ApiHistoryRefreshRoute
  '/api/loops/$id': typeof ApiLoopsIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/models/$id': typeof ApiModelsIdRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/clear': typeof ApiQueueClearRoute
  '/api/ranking/daily': typeof ApiRankingDailyRoute
  '/api/variants/build': typeof ApiVariantsBuildRoute
  '/api/accounts/$id/status': typeof ApiAccountsIdStatusRoute
  '/api/accounts/$id/validate': typeof ApiAccountsIdValidateRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/link': typeof ApiAuthInstagramLinkRoute
  '/api/drive/folder/$id': typeof ApiDriveFolderIdRoute
  '/api/public/drive/$id': typeof ApiPublicDriveIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/contingency': typeof AppContingencyRoute
  '/history': typeof AppHistoryRoute
  '/queue': typeof AppQueueRoute
  '/ranking': typeof AppRankingRoute
  '/warmup': typeof AppWarmupRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/contingency': typeof ApiContingencyRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/loops': typeof ApiLoopsRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/api/ranking': typeof ApiRankingRouteWithChildren
  '/': typeof AppIndexRoute
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/contingency/$id': typeof ApiContingencyIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/history/refresh': typeof ApiHistoryRefreshRoute
  '/api/loops/$id': typeof ApiLoopsIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/models/$id': typeof ApiModelsIdRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/clear': typeof ApiQueueClearRoute
  '/api/ranking/daily': typeof ApiRankingDailyRoute
  '/api/variants/build': typeof ApiVariantsBuildRoute
  '/api/accounts/$id/status': typeof ApiAccountsIdStatusRoute
  '/api/accounts/$id/validate': typeof ApiAccountsIdValidateRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/link': typeof ApiAuthInstagramLinkRoute
  '/api/drive/folder/$id': typeof ApiDriveFolderIdRoute
  '/api/public/drive/$id': typeof ApiPublicDriveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/contingency': typeof AppContingencyRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/warmup': typeof AppWarmupRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/contingency': typeof ApiContingencyRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/loops': typeof ApiLoopsRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/api/ranking': typeof ApiRankingRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/contingency/$id': typeof ApiContingencyIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/history/refresh': typeof ApiHistoryRefreshRoute
  '/api/loops/$id': typeof ApiLoopsIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/models/$id': typeof ApiModelsIdRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/clear': typeof ApiQueueClearRoute
  '/api/ranking/daily': typeof ApiRankingDailyRoute
  '/api/variants/build': typeof ApiVariantsBuildRoute
  '/api/accounts/$id/status': typeof ApiAccountsIdStatusRoute
  '/api/accounts/$id/validate': typeof ApiAccountsIdValidateRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/link': typeof ApiAuthInstagramLinkRoute
  '/api/drive/folder/$id': typeof ApiDriveFolderIdRoute
  '/api/public/drive/$id': typeof ApiPublicDriveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/contingency'
    | '/history'
    | '/queue'
    | '/ranking'
    | '/warmup'
    | '/api/accounts'
    | '/api/contingency'
    | '/api/history'
    | '/api/loops'
    | '/api/models'
    | '/api/queue'
    | '/api/ranking'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/contingency/$id'
    | '/api/cron/tick'
    | '/api/history/refresh'
    | '/api/loops/$id'
    | '/api/media/upload'
    | '/api/models/$id'
    | '/api/queue/$id'
    | '/api/queue/clear'
    | '/api/ranking/daily'
    | '/api/variants/build'
    | '/api/accounts/$id/status'
    | '/api/accounts/$id/validate'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/link'
    | '/api/drive/folder/$id'
    | '/api/public/drive/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/contingency'
    | '/history'
    | '/queue'
    | '/ranking'
    | '/warmup'
    | '/api/accounts'
    | '/api/contingency'
    | '/api/history'
    | '/api/loops'
    | '/api/models'
    | '/api/queue'
    | '/api/ranking'
    | '/'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/contingency/$id'
    | '/api/cron/tick'
    | '/api/history/refresh'
    | '/api/loops/$id'
    | '/api/media/upload'
    | '/api/models/$id'
    | '/api/queue/$id'
    | '/api/queue/clear'
    | '/api/ranking/daily'
    | '/api/variants/build'
    | '/api/accounts/$id/status'
    | '/api/accounts/$id/validate'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/link'
    | '/api/drive/folder/$id'
    | '/api/public/drive/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/accounts'
    | '/_app/contingency'
    | '/_app/history'
    | '/_app/queue'
    | '/_app/ranking'
    | '/_app/warmup'
    | '/api/accounts'
    | '/api/contingency'
    | '/api/history'
    | '/api/loops'
    | '/api/models'
    | '/api/queue'
    | '/api/ranking'
    | '/_app/'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/contingency/$id'
    | '/api/cron/tick'
    | '/api/history/refresh'
    | '/api/loops/$id'
    | '/api/media/upload'
    | '/api/models/$id'
    | '/api/queue/$id'
    | '/api/queue/clear'
    | '/api/ranking/daily'
    | '/api/variants/build'
    | '/api/accounts/$id/status'
    | '/api/accounts/$id/validate'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/link'
    | '/api/drive/folder/$id'
    | '/api/public/drive/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAccountsRoute: typeof ApiAccountsRouteWithChildren
  ApiContingencyRoute: typeof ApiContingencyRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiLoopsRoute: typeof ApiLoopsRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRouteWithChildren
  ApiQueueRoute: typeof ApiQueueRouteWithChildren
  ApiRankingRoute: typeof ApiRankingRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthCallbackIgRoute: typeof ApiAuthCallbackIgRoute
  ApiAuthInstagramRoute: typeof ApiAuthInstagramRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiVariantsBuildRoute: typeof ApiVariantsBuildRoute
  ApiDriveFolderIdRoute: typeof ApiDriveFolderIdRoute
  ApiPublicDriveIdRoute: typeof ApiPublicDriveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ranking': {
      id: '/api/ranking'
      path: '/api/ranking'
      fullPath: '/api/ranking'
      preLoaderRoute: typeof ApiRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loops': {
      id: '/api/loops'
      path: '/api/loops'
      fullPath: '/api/loops'
      preLoaderRoute: typeof ApiLoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contingency': {
      id: '/api/contingency'
      path: '/api/contingency'
      fullPath: '/api/contingency'
      preLoaderRoute: typeof ApiContingencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warmup': {
      id: '/_app/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof AppWarmupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contingency': {
      id: '/_app/contingency'
      path: '/contingency'
      fullPath: '/contingency'
      preLoaderRoute: typeof AppContingencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/variants/build': {
      id: '/api/variants/build'
      path: '/api/variants/build'
      fullPath: '/api/variants/build'
      preLoaderRoute: typeof ApiVariantsBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ranking/daily': {
      id: '/api/ranking/daily'
      path: '/daily'
      fullPath: '/api/ranking/daily'
      preLoaderRoute: typeof ApiRankingDailyRouteImport
      parentRoute: typeof ApiRankingRoute
    }
    '/api/queue/clear': {
      id: '/api/queue/clear'
      path: '/clear'
      fullPath: '/api/queue/clear'
      preLoaderRoute: typeof ApiQueueClearRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id': {
      id: '/api/queue/$id'
      path: '/$id'
      fullPath: '/api/queue/$id'
      preLoaderRoute: typeof ApiQueueIdRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/models/$id': {
      id: '/api/models/$id'
      path: '/$id'
      fullPath: '/api/models/$id'
      preLoaderRoute: typeof ApiModelsIdRouteImport
      parentRoute: typeof ApiModelsRoute
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loops/$id': {
      id: '/api/loops/$id'
      path: '/$id'
      fullPath: '/api/loops/$id'
      preLoaderRoute: typeof ApiLoopsIdRouteImport
      parentRoute: typeof ApiLoopsRoute
    }
    '/api/history/refresh': {
      id: '/api/history/refresh'
      path: '/refresh'
      fullPath: '/api/history/refresh'
      preLoaderRoute: typeof ApiHistoryRefreshRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contingency/$id': {
      id: '/api/contingency/$id'
      path: '/$id'
      fullPath: '/api/contingency/$id'
      preLoaderRoute: typeof ApiContingencyIdRouteImport
      parentRoute: typeof ApiContingencyRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram': {
      id: '/api/auth/instagram'
      path: '/api/auth/instagram'
      fullPath: '/api/auth/instagram'
      preLoaderRoute: typeof ApiAuthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback-ig': {
      id: '/api/auth/callback-ig'
      path: '/api/auth/callback-ig'
      fullPath: '/api/auth/callback-ig'
      preLoaderRoute: typeof ApiAuthCallbackIgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/$id': {
      id: '/api/accounts/$id'
      path: '/$id'
      fullPath: '/api/accounts/$id'
      preLoaderRoute: typeof ApiAccountsIdRouteImport
      parentRoute: typeof ApiAccountsRoute
    }
    '/api/public/drive/$id': {
      id: '/api/public/drive/$id'
      path: '/api/public/drive/$id'
      fullPath: '/api/public/drive/$id'
      preLoaderRoute: typeof ApiPublicDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/folder/$id': {
      id: '/api/drive/folder/$id'
      path: '/api/drive/folder/$id'
      fullPath: '/api/drive/folder/$id'
      preLoaderRoute: typeof ApiDriveFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram/link': {
      id: '/api/auth/instagram/link'
      path: '/link'
      fullPath: '/api/auth/instagram/link'
      preLoaderRoute: typeof ApiAuthInstagramLinkRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
    '/api/auth/instagram/callback': {
      id: '/api/auth/instagram/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram/callback'
      preLoaderRoute: typeof ApiAuthInstagramCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
    '/api/accounts/$id/validate': {
      id: '/api/accounts/$id/validate'
      path: '/validate'
      fullPath: '/api/accounts/$id/validate'
      preLoaderRoute: typeof ApiAccountsIdValidateRouteImport
      parentRoute: typeof ApiAccountsIdRoute
    }
    '/api/accounts/$id/status': {
      id: '/api/accounts/$id/status'
      path: '/status'
      fullPath: '/api/accounts/$id/status'
      preLoaderRoute: typeof ApiAccountsIdStatusRouteImport
      parentRoute: typeof ApiAccountsIdRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppContingencyRoute: typeof AppContingencyRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRankingRoute: typeof AppRankingRoute
  AppWarmupRoute: typeof AppWarmupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppContingencyRoute: AppContingencyRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppQueueRoute: AppQueueRoute,
  AppRankingRoute: AppRankingRoute,
  AppWarmupRoute: AppWarmupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAccountsIdRouteChildren {
  ApiAccountsIdStatusRoute: typeof ApiAccountsIdStatusRoute
  ApiAccountsIdValidateRoute: typeof ApiAccountsIdValidateRoute
}

const ApiAccountsIdRouteChildren: ApiAccountsIdRouteChildren = {
  ApiAccountsIdStatusRoute: ApiAccountsIdStatusRoute,
  ApiAccountsIdValidateRoute: ApiAccountsIdValidateRoute,
}

const ApiAccountsIdRouteWithChildren = ApiAccountsIdRoute._addFileChildren(
  ApiAccountsIdRouteChildren,
)

interface ApiAccountsRouteChildren {
  ApiAccountsIdRoute: typeof ApiAccountsIdRouteWithChildren
}

const ApiAccountsRouteChildren: ApiAccountsRouteChildren = {
  ApiAccountsIdRoute: ApiAccountsIdRouteWithChildren,
}

const ApiAccountsRouteWithChildren = ApiAccountsRoute._addFileChildren(
  ApiAccountsRouteChildren,
)

interface ApiContingencyRouteChildren {
  ApiContingencyIdRoute: typeof ApiContingencyIdRoute
}

const ApiContingencyRouteChildren: ApiContingencyRouteChildren = {
  ApiContingencyIdRoute: ApiContingencyIdRoute,
}

const ApiContingencyRouteWithChildren = ApiContingencyRoute._addFileChildren(
  ApiContingencyRouteChildren,
)

interface ApiHistoryRouteChildren {
  ApiHistoryRefreshRoute: typeof ApiHistoryRefreshRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryRefreshRoute: ApiHistoryRefreshRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

interface ApiLoopsRouteChildren {
  ApiLoopsIdRoute: typeof ApiLoopsIdRoute
}

const ApiLoopsRouteChildren: ApiLoopsRouteChildren = {
  ApiLoopsIdRoute: ApiLoopsIdRoute,
}

const ApiLoopsRouteWithChildren = ApiLoopsRoute._addFileChildren(
  ApiLoopsRouteChildren,
)

interface ApiModelsRouteChildren {
  ApiModelsIdRoute: typeof ApiModelsIdRoute
}

const ApiModelsRouteChildren: ApiModelsRouteChildren = {
  ApiModelsIdRoute: ApiModelsIdRoute,
}

const ApiModelsRouteWithChildren = ApiModelsRoute._addFileChildren(
  ApiModelsRouteChildren,
)

interface ApiQueueRouteChildren {
  ApiQueueIdRoute: typeof ApiQueueIdRoute
  ApiQueueClearRoute: typeof ApiQueueClearRoute
}

const ApiQueueRouteChildren: ApiQueueRouteChildren = {
  ApiQueueIdRoute: ApiQueueIdRoute,
  ApiQueueClearRoute: ApiQueueClearRoute,
}

const ApiQueueRouteWithChildren = ApiQueueRoute._addFileChildren(
  ApiQueueRouteChildren,
)

interface ApiRankingRouteChildren {
  ApiRankingDailyRoute: typeof ApiRankingDailyRoute
}

const ApiRankingRouteChildren: ApiRankingRouteChildren = {
  ApiRankingDailyRoute: ApiRankingDailyRoute,
}

const ApiRankingRouteWithChildren = ApiRankingRoute._addFileChildren(
  ApiRankingRouteChildren,
)

interface ApiAuthInstagramRouteChildren {
  ApiAuthInstagramCallbackRoute: typeof ApiAuthInstagramCallbackRoute
  ApiAuthInstagramLinkRoute: typeof ApiAuthInstagramLinkRoute
}

const ApiAuthInstagramRouteChildren: ApiAuthInstagramRouteChildren = {
  ApiAuthInstagramCallbackRoute: ApiAuthInstagramCallbackRoute,
  ApiAuthInstagramLinkRoute: ApiAuthInstagramLinkRoute,
}

const ApiAuthInstagramRouteWithChildren =
  ApiAuthInstagramRoute._addFileChildren(ApiAuthInstagramRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAccountsRoute: ApiAccountsRouteWithChildren,
  ApiContingencyRoute: ApiContingencyRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiLoopsRoute: ApiLoopsRouteWithChildren,
  ApiModelsRoute: ApiModelsRouteWithChildren,
  ApiQueueRoute: ApiQueueRouteWithChildren,
  ApiRankingRoute: ApiRankingRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthCallbackIgRoute: ApiAuthCallbackIgRoute,
  ApiAuthInstagramRoute: ApiAuthInstagramRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiVariantsBuildRoute: ApiVariantsBuildRoute,
  ApiDriveFolderIdRoute: ApiDriveFolderIdRoute,
  ApiPublicDriveIdRoute: ApiPublicDriveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
