/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiQueueRouteImport } from './routes/api/queue'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as ApiRevealKeyRouteImport } from './routes/api/_reveal-key'
import { Route as AppWarmupRouteImport } from './routes/_app.warmup'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppContingencyRouteImport } from './routes/_app.contingency'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as ApiQueueIdRouteImport } from './routes/api/queue.$id'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media.upload'
import { Route as ApiCronTickRouteImport } from './routes/api/cron.tick'
import { Route as ApiAuthInstagramRouteImport } from './routes/api/auth.instagram'
import { Route as ApiAuthCallbackIgRouteImport } from './routes/api/auth.callback-ig'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth.callback'
import { Route as ApiAccountsIdRouteImport } from './routes/api/accounts.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevealKeyRoute = ApiRevealKeyRouteImport.update({
  id: '/api/_reveal-key',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarmupRoute = AppWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppContingencyRoute = AppContingencyRouteImport.update({
  id: '/contingency',
  path: '/contingency',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const ApiQueueIdRoute = ApiQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramRoute = ApiAuthInstagramRouteImport.update({
  id: '/api/auth/instagram',
  path: '/api/auth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackIgRoute = ApiAuthCallbackIgRouteImport.update({
  id: '/api/auth/callback-ig',
  path: '/api/auth/callback-ig',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsIdRoute = ApiAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/contingency': typeof AppContingencyRoute
  '/history': typeof AppHistoryRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/warmup': typeof AppWarmupRoute
  '/api': typeof ApiRevealKeyRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/api/accounts/$id': typeof ApiAccountsIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRoute
  '/contingency': typeof AppContingencyRoute
  '/history': typeof AppHistoryRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/warmup': typeof AppWarmupRoute
  '/api': typeof ApiRevealKeyRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/': typeof AppIndexRoute
  '/api/accounts/$id': typeof ApiAccountsIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/contingency': typeof AppContingencyRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/warmup': typeof AppWarmupRoute
  '/api/_reveal-key': typeof ApiRevealKeyRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/api/accounts/$id': typeof ApiAccountsIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/callback-ig': typeof ApiAuthCallbackIgRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/contingency'
    | '/history'
    | '/queue'
    | '/settings'
    | '/warmup'
    | '/api'
    | '/api/accounts'
    | '/api/history'
    | '/api/queue'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/cron/tick'
    | '/api/media/upload'
    | '/api/queue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/contingency'
    | '/history'
    | '/queue'
    | '/settings'
    | '/warmup'
    | '/api'
    | '/api/accounts'
    | '/api/history'
    | '/api/queue'
    | '/'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/cron/tick'
    | '/api/media/upload'
    | '/api/queue/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/contingency'
    | '/_app/history'
    | '/_app/queue'
    | '/_app/settings'
    | '/_app/warmup'
    | '/api/_reveal-key'
    | '/api/accounts'
    | '/api/history'
    | '/api/queue'
    | '/_app/'
    | '/api/accounts/$id'
    | '/api/auth/callback'
    | '/api/auth/callback-ig'
    | '/api/auth/instagram'
    | '/api/cron/tick'
    | '/api/media/upload'
    | '/api/queue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiRevealKeyRoute: typeof ApiRevealKeyRoute
  ApiAccountsRoute: typeof ApiAccountsRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiQueueRoute: typeof ApiQueueRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthCallbackIgRoute: typeof ApiAuthCallbackIgRoute
  ApiAuthInstagramRoute: typeof ApiAuthInstagramRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/_reveal-key': {
      id: '/api/_reveal-key'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRevealKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warmup': {
      id: '/_app/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof AppWarmupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contingency': {
      id: '/_app/contingency'
      path: '/contingency'
      fullPath: '/contingency'
      preLoaderRoute: typeof AppContingencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/queue/$id': {
      id: '/api/queue/$id'
      path: '/$id'
      fullPath: '/api/queue/$id'
      preLoaderRoute: typeof ApiQueueIdRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram': {
      id: '/api/auth/instagram'
      path: '/api/auth/instagram'
      fullPath: '/api/auth/instagram'
      preLoaderRoute: typeof ApiAuthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback-ig': {
      id: '/api/auth/callback-ig'
      path: '/api/auth/callback-ig'
      fullPath: '/api/auth/callback-ig'
      preLoaderRoute: typeof ApiAuthCallbackIgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/$id': {
      id: '/api/accounts/$id'
      path: '/$id'
      fullPath: '/api/accounts/$id'
      preLoaderRoute: typeof ApiAccountsIdRouteImport
      parentRoute: typeof ApiAccountsRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppContingencyRoute: typeof AppContingencyRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppQueueRoute: typeof AppQueueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWarmupRoute: typeof AppWarmupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppContingencyRoute: AppContingencyRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppQueueRoute: AppQueueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWarmupRoute: AppWarmupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAccountsRouteChildren {
  ApiAccountsIdRoute: typeof ApiAccountsIdRoute
}

const ApiAccountsRouteChildren: ApiAccountsRouteChildren = {
  ApiAccountsIdRoute: ApiAccountsIdRoute,
}

const ApiAccountsRouteWithChildren = ApiAccountsRoute._addFileChildren(
  ApiAccountsRouteChildren,
)

interface ApiQueueRouteChildren {
  ApiQueueIdRoute: typeof ApiQueueIdRoute
}

const ApiQueueRouteChildren: ApiQueueRouteChildren = {
  ApiQueueIdRoute: ApiQueueIdRoute,
}

const ApiQueueRouteWithChildren = ApiQueueRoute._addFileChildren(
  ApiQueueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiRevealKeyRoute: ApiRevealKeyRoute,
  ApiAccountsRoute: ApiAccountsRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiQueueRoute: ApiQueueRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthCallbackIgRoute: ApiAuthCallbackIgRoute,
  ApiAuthInstagramRoute: ApiAuthInstagramRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
