{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "insta-manager",
  "compatibility_date": "2025-09-24",
  "compatibility_flags": ["nodejs_compat"],
  "main": "src/server.ts",

  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "insta-manager",
      "database_id": "ed1acecd-5ee6-45ed-8d61-ef03119781ce"
    }
  ],

  "r2_buckets": [
    {
      "binding": "MEDIA",
      "bucket_name": "insta-media"
    }
  ],

  "triggers": {
    "crons": ["* * * * *"]
  },

  "vars": {
    "APP_ENV": "production"
  }
}
